# 通用设置
mode: 'train' # 'train' (训练) 或 'generate' (生成)
device_priority: ['xpu', 'cuda', 'cpu'] # 计算设备的选择优先级

# 路径设置
paths:
  dataset_dir: 'dataSet'       # 数据集存放的文件夹名
  results_dir: 'results'    # 生成的图片存放的文件夹名
  # 检查点路径将根据设备类型动态确定
  # 例如: checkpoints_xpu/checkpoint.pth

# 训练设置
train:
  epochs: 200
  lr: 0.0002
  batch_size:
    windows: 64
    linux: 128
    macos: 64
  checkpoint_freq: 50        # 每 N 轮保存一次检查点
  generate_image_freq: 50   # 每 N 轮生成一次样本图片

# 数据加载器设置
dataloader:
  num_workers:
    windows: 0
    linux: 4
    macos: 0

# 生成设置
generate:
  num_images: 64
  # 用于生成的模型将从最新的检查点加载